---
version: '3'
services:
    wordpress:
        build: .
        image: my-wordpress
        ports:
            - 8080:80
        environment:
            - WORDPRESS_DB_HOST=db
            - WORDPRESS_DB_USER=root
            - WORDPRESS_DB_PASSWORD=myPassw0rd
            - WORDPRESS_DB_NAME=wp
            - WORDPRESS_TABLE_PREFIX=wp_

    db:
        image: percona
        environment:
            - MYSQL_ROOT_PASSWORD=myPassw0rd

